apiVersion: v1
kind: Service
metadata:
  name: mysql-local
  namespace: cantina
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: cantina-mysql
  ports:
    - name: mysql
      port: 3307
      targetPort: mysql
