apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cantina
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cantina
                port:
                  name: http
