apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cantina
resources:
  - app-config.yaml
  - app-pvc.yaml
  - app-deployment.yaml
  - app-service.yaml
  - mysql-service.yaml
  - mysql-statefulset.yaml
configMapGenerator:
  - name: mysql-init
    files:
      - 01-schema.sql=schema.sql
      - 02-bootstrap-admin.sh=bootstrap-admin.sh
generatorOptions:
  disableNameSuffixHash: true
